services:
  apk-modder:
    image: ${APK_MODDER_IMAGE:-ghcr.io/tanyuxiao/apk-modder:latest}
    pull_policy: always
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - HOST=0.0.0.0
